create table if not exists public.resource_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  first_name text not null,
  resource_slug text not null,
  source text not null,
  privacy_consent boolean not null default false,
  marketing_consent boolean not null default false,
  requested_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint resource_requests_email_resource_key
    unique (email, resource_slug)
);

alter table public.resource_requests enable row level security;

comment on table public.resource_requests is
  'Solicitudes de eBooks y otros recursos capturadas desde genbakai.com.';
